project_id = "ccfsxwmvgyxsoscofqoh"

[functions.process-campaign]
verify_jwt = false

[functions.manage-contacts]
verify_jwt = false

[functions.system-stats]
verify_jwt = false

[functions.sync-devices]
verify_jwt = false

[functions.evolution-connect]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.join-group]
verify_jwt = false

[functions.warmup-execute]
verify_jwt = false

[functions.run-scheduled-campaigns]
verify_jwt = false

[functions.report-wa]
verify_jwt = false

[functions.webhook-instances]
verify_jwt = false

[functions.webhook-dispatch]
verify_jwt = false

[functions.warmup-engine]
verify_jwt = false

[functions.warmup-tick]
verify_jwt = false

[functions.manage-devices]
verify_jwt = false

[functions.process-message-queue]
verify_jwt = false

[functions.report-wa-cron]
verify_jwt = false

[functions.wa-lifecycle]
verify_jwt = false

[functions.provision-trial]
verify_jwt = false

[functions.whapi-chats]
verify_jwt = false

[functions.trial-cleanup]
verify_jwt = false
