project_id = "ccfsxwmvgyxsoscofqoh"

[functions.process-campaign]
verify_jwt = false

[functions.manage-contacts]
verify_jwt = false

[functions.system-stats]
verify_jwt = false

[functions.sync-devices]
verify_jwt = false

[functions.evolution-connect]
verify_jwt = false
