ALTER TABLE public.campaign_contacts
  ADD COLUMN IF NOT EXISTS var1 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS var2 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS var3 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS var4 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS var5 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS var6 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS var7 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS var8 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS var9 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS var10 text DEFAULT '';