
ALTER TABLE public.contacts
  ADD COLUMN IF NOT EXISTS var1 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS var2 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS var3 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS var4 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS var5 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS var6 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS var7 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS var8 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS var9 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS var10 text NOT NULL DEFAULT '';
